name: hello github action

on:
  push: [main]



jobs:
  greet:
    runs-on: ubuntu:latest

      steps:
        - name: checkout code
          uses: actions/checkout@v7

        - name: say hello 
          run:  ech " Hello  from Github Actions!"
