name: GitHub Hosted Runners

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps: 
      - name: Show runner information
        run: |
          echo "OS : ubuntu"
          echo "Hostname: $(hostname)"
          echo "USER : $USER"
          echo  "USER: $(whoami)"
  windows:
    runs-on: windows-latest
    steps:
      - name: Show runner information
        shell: pwsh
        run: |
          Write-Host "OS: Windows"
          Write-Host "Hostname: $env:COMPUTERNAME"
          Write-Host "User: $env:USERNAME"

  macos:
    runs-on:  macos-latest
    steps: 
      - name: Show runner information
        run: |
          echo "OS: macOS"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"

