name: Multi Job Workflow

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        - name: checkout code
          uses: actions/checkout@v7

        - name: build run
          run: echo "Building the app"

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
        - name: test
          run: echo "Running tests"

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
        - name: deploy
          run: echo "Deploying"