name: Scheduled Workflow

on:
  schedule:
    - cron: "55 11 04 09 5"


jobs: 
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - name: Show scheduled execution
        run:  echo "Scheduled workflow is running!"

