name: GitHub Secrets

env:
    SECRET_MESSAGE: ${{secrets.MY_SECRET_MESSAGE}}

on:
  workflow_dispatch:

jobs:
    secrets-tests:
        runs-on: ubuntu-latest
        steps:
          - name: check if secret is set
            env: 
              SECRET_MESSAGE: ${{secrets.MY_SECRET_MESSAGE}}
            run: |
                if [ -n "$SECRET_MESSAGE" ]; then
                    echo "Secret is set : true"
                else
                    echo " secrets is set : false"
                fi

          - name: Try printing the secrets
            run: |
                echo " MY SECRET MEASSAGE IS: ${{secrets.MY_SECRET_MESSAGE}}"