name: Secrets as Environment Variables

on:
  workflow_dispatch:

jobs:
    secret-env-test:
        runs-on: ubuntu-latest
        steps:
            - name: Use secret as environment variable
              env: 
                SECRET_MESSAGE: ${{secrets.MY_SECRET_MESSAGE}}
              run: |
                 if [ -n "$SECRET_MESSAGE" ]; then
                        echo "Secret environment variable is available."
                    else
                        echo "Secret environment variable is not available."
                        exit 1
                    fi


            - name: Check Docker credentials
              env:
                DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
                DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
              run: |
                if [ -n "$DOCKER_USERNAME" ]; then
                    echo "Docker username secret is available."
                else
                    echo "Docker username secret is not missing."
                    exit 1
                fi

                if [ -n "$DOCKER_TOKEN" ]; then
                    echo "Docker token secret is available."
                else
                    echo "Docker token secret is missing."
                    exit 1
                fi